import type { Metadata } from "next";
import { LegalPageShell, type LegalSection } from "@/components/legal/LegalPageShell";
import { SUPPORT_EMAIL, createLegalMetadata, createSupportMailto } from "@/lib/legal";

export const metadata: Metadata = createLegalMetadata({
  path: "/privacy",
  title: "Privacy Policy",
  description:
    "How TechInView collects, uses, stores, and shares account data, interview data, analytics events, payment records, and support requests.",
});

const sections: LegalSection[] = [
  {
    title: "What this policy covers",
    content: (
      <>
        <p>
          This Privacy Policy explains how TechInView collects, uses, stores,
          and shares information when you visit the site, create an account,
          practice interview problems, purchase interview packs, or contact
          support.
        </p>
        <p>
          TechInView is an interview preparation product for software
          engineers. Because the core experience includes voice, code, scoring,
          and payments, this policy covers each of those product surfaces in one
          place.
        </p>
      </>
    ),
  },
  {
    title: "Information we collect",
    content: (
      <>
        <p>Depending on how you use TechInView, we may collect:</p>
        <ul>
          <li>
            Account and profile data such as your email address, auth provider,
            display name, username, public bio, target company, experience
            level, preferred language, and profile links.
          </li>
          <li>
            Interview and practice data such as selected problems, code
            submissions, execution results, timestamps, scores, feedback,
            transcripts, and interview state.
          </li>
          <li>
            Voice-related data such as live microphone audio, audio generated by
            the interviewer, transcripts, and metadata needed to run the voice
            experience.
          </li>
          <li>
            Usage and device data such as browser details, approximate
            geolocation derived from IP for pricing or security, logs, and
            analytics events.
          </li>
          <li>
            Payment records such as Razorpay order identifiers, payment
            identifiers, pack type, currency, and credit fulfillment status. We
            do not store full card numbers or bank details on our own servers.
          </li>
          <li>
            Support communications, including the contents of emails you send to{" "}
            <a href={createSupportMailto({ subject: "Privacy question" })}>
              {SUPPORT_EMAIL}
            </a>
            .
          </li>
        </ul>
      </>
    ),
  },
  {
    title: "How we use information",
    content: (
      <>
        <p>We use collected information to:</p>
        <ul>
          <li>create and secure your account;</li>
          <li>run practice sessions, AI interviews, scoring, and feedback;</li>
          <li>process payments, issue credits, and review refund requests;</li>
          <li>monitor reliability, investigate bugs, and prevent abuse;</li>
          <li>understand product usage through analytics and improve the service;</li>
          <li>respond to support, legal, privacy, and billing requests.</li>
        </ul>
      </>
    ),
  },
  {
    title: "Voice, transcript, and AI processing",
    content: (
      <>
        <p>
          TechInView may process microphone audio, transcripts, prompts, code,
          and interview context through third-party infrastructure in order to
          deliver the interview experience. That can include speech-to-text,
          text generation, text-to-speech, hosting, logging, analytics, and code
          execution services.
        </p>
        <p>
          Voice or transcript data may be stored when needed to render results,
          troubleshoot the experience, support abuse prevention, or fulfill
          support requests. We do not use your content for advertising.
        </p>
      </>
    ),
  },
  {
    title: "When we share information",
    content: (
      <>
        <p>
          We do not sell your personal information. We may share data with
          service providers that help us operate TechInView, including providers
          for authentication and database infrastructure, AI and voice
          processing, payments, analytics, hosting, and code execution.
        </p>
        <p>
          Based on the current product stack, that may include Supabase,
          Anthropic, Deepgram, Razorpay, PostHog, Vercel, Railway, and Piston or
          similar infrastructure providers. We may also disclose information if
          required to comply with law, protect users, or enforce our Terms.
        </p>
      </>
    ),
  },
  {
    title: "Retention and security",
    content: (
      <>
        <p>
          We keep information for as long as it is reasonably necessary to run
          the service, keep interview history available, meet accounting
          obligations, prevent fraud, and resolve disputes. Retention periods may
          differ by data type.
        </p>
        <p>
          We use reasonable administrative, technical, and organizational
          measures to protect information, but no system can guarantee absolute
          security. If you believe your account or data has been compromised,
          contact us promptly at{" "}
          <a href={createSupportMailto({ subject: "Security or privacy issue" })}>
            {SUPPORT_EMAIL}
          </a>
          .
        </p>
      </>
    ),
  },
  {
    title: "Your choices and requests",
    content: (
      <>
        <p>
          You can update certain profile information inside your account. You
          can also email us to request account access, correction, deletion, or
          help with a privacy question.
        </p>
        <p>
          We may need to verify your identity before completing sensitive
          requests. Some data may be retained when required for legal,
          accounting, fraud-prevention, or legitimate product operations.
        </p>
      </>
    ),
  },
  {
    title: "Changes and contact",
    content: (
      <>
        <p>
          We may update this Privacy Policy as the product evolves. When we make
          material changes, we will update the date on this page and may provide
          additional notice inside the product when appropriate.
        </p>
        <p>
          For privacy questions, support issues, or data requests, email{" "}
          <a href={createSupportMailto({ subject: "TechInView privacy request" })}>
            {SUPPORT_EMAIL}
          </a>{" "}
          or visit the <a href="/contact">Contact page</a>.
        </p>
      </>
    ),
  },
];

export default function PrivacyPage() {
  return (
    <LegalPageShell
      currentPath="/privacy"
      title="Privacy Policy"
      description="How TechInView handles account details, interview data, voice transcripts, payments, analytics, and support communications."
      sections={sections}
    />
  );
}
